name = "Kuber"
uuid = "87e52247-8a1b-5e01-9430-8fbcac83a23a"
authors = ["Tanmay Mohapatra <tanmaykm@gmail.com>"]
keywords = ["kubernetes", "client"]
license = "MIT"
desc = "Julia Kubernetes Client"
version = "0.3.1"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Swagger = "2d69052b-6a58-5cd9-a030-a48559c324ac"

[compat]
HTTP = "~ 0.8"
Swagger = "~ 0.2"
JSON = "~ 0.21"
julia = "~ 1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
